name: Build

on: [push]

env:
  PROJECT_GENERATOR_VERSION: 3

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        id: create_release

  build_linux:
    needs: [create_release]
    runs-on: ubuntu-latest
    env:
      PREMAKE5_URL: https://github.com/danielga/garrysmod_common/releases/download/premake-build%2F5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          set -ex

          sudo apt-get -y install ppa-purge
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get -y install gcc-multilib g++-multilib libssl-dev libboost-dev libboost-system-dev libssl-dev:i386 libboost-dev:i386 libboost-system-dev:i386

          wget "${PREMAKE5_URL}" -O /tmp/premake.tar.gz
          sudo tar -xzf /tmp/premake.tar.gz -C /usr/local/bin

          premake5 --file=BuildProjects.lua --os=linux gmake
          cd solutions/linux-gmake
          gmake config=release_x86_64 -j$(nproc)
          gmake config=release_x86 -j$(nproc)
      - name: Upload release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          tag_name: ${{ needs.create_release.outputs.tag-name }}
          fail_on_unmatched_files: true
          files: "out/**/*.dll"
